name: Build Windows executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # If you have requirements.txt, uncomment below
          # pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile main.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-windows-exe
          path: dist/main.exe
